import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter, Poppins } from "next/font/google";
import { Layout } from "@/components/layout";
export const metadata: Metadata = {
    title: "Geraldo Neto Treinador",
    description: "Generated by create next app",
};

export const poppins = Poppins({
    weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
    subsets: ["latin"],
    display: "swap",
});

export const inter = Inter({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-inter",
    display: "swap",
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR" suppressHydrationWarning className="scroll-smooth">
            <body
                className={`${inter.variable} ${poppins.className} antialiased bg-background`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Layout>{children}</Layout>
                </ThemeProvider>
            </body>
        </html>
    );
}
